pretrain:  './vit-b-16-32f.pt'
seed: 1024
data:
    dataset: ucf
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 2
    workers: 1
    num_classes: 2
    image_tmpl: 'img_{:05d}.jpg'
    val_list: '' #
    label_list: ''
    index_bias: 1
    input_size: 224
    randaug:
        N: 0 #2
        M: 0  #9
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True 
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_ucf
    sim_header: "Transf"   #Transf   meanP  LSTM Conv_1D Transf_cls
    fix_text: False
    fix_img: False
    describe:
logging:
    print_freq: 10
    eval_freq: 1